version: "3.8"
services:
  elasticsearch:
    container_name: brienne-elasticsearch
    image: elasticsearch:7.6.0
    networks:
      - brienne
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: elastic
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "true"
  kibana:
    container_name: brienne-kibana
    image: kibana:7.6.0
    networks:
      - brienne
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
networks:
  brienne:
    name: brienne